// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCssgF3G_afAzRVG3V9pkbZruWN_2RIM-Y',
    appId: '1:209876187617:web:3a6576d4bda25c7595faa0',
    messagingSenderId: '209876187617',
    projectId: 'ditto-713d5',
    authDomain: 'ditto-713d5.firebaseapp.com',
    storageBucket: 'ditto-713d5.firebasestorage.app',
    measurementId: 'G-3RZ2NG52MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8f_ygdUd5XkpomiMP7NhfvriIMMBHpfE',
    appId: '1:209876187617:android:077dad42abf6772c95faa0',
    messagingSenderId: '209876187617',
    projectId: 'ditto-713d5',
    storageBucket: 'ditto-713d5.firebasestorage.app',
  );
}
